### ISSUE TITLE
Create cross-platform binary/script

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/check_if_email_exists#4]
Right now this is only a script, which only works on *nix systems. It'd be wise to rewrite this in another language, which can be run on different platforms.

**Comment by hadisfr** [comment]
What do you mean by _binary_ exactly? 🤔 Is a python port of this script good enough?
And… rewrite in another language would be another project. Or you want to add another implementation next to the current one in the same repo?

**Comment by amaurymartiny** [comment]
Right, a python port would definitely work, I changed the title.

I wish to improve on this implementation. One improvement would be to parallelize the telnet calls so that it resolves faster, afaik bash doesn't support threads. Another improvement would be for it to work on all platforms.

We can keep the bash version in another folder in the same repo (if people want that), but I think the main program should be rewritten in a more advanced language.

**Comment by hadisfr** [comment]
Actually, I don't how how much free time I've got right now. If I write any script, I'll tell you.
