### ISSUE TITLE
Serverless version of this service

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/check_if_email_exists#9]
To mimic the service proposed by the websites mentioned in the README, it would be good to have an endpoint that takes an email in a query parameter as input, and outputs true/false.

I have never tried serverless, but I think it would fit here, i.e. no need to code a web server in Rust, just a function that takes a HTTP request in input, and outputs a HTTP response.

Some requirements about this serverless platform:
- supports Rust, obviously
- is free (or at least has a free tier)
- SMTP ports open

Some possible solutions:
- **AWS lambda** (they have a Rust runtime https://aws.amazon.com/blogs/opensource/rust-runtime-for-aws-lambda/)
- ~**Zeit**: they already propose [serverless Docker](https://zeit.co/blog/serverless-docker#serverless-rust-(global)), but it's not ideal, so probably better to wait for the serverless lambda functions with Rust: https://twitter.com/rauchg/status/1076150773099126784~ Not possible: https://spectrum.chat/thread/25377e2c-fdd4-44c2-ae45-70751e9f5db6
- **serverless.com** with https://github.com/softprops/serverless-rust
- **apex** http://apex.run/

**Comment by shinebayar-g** [comment]
Hello @amaurymartiny , thanks for the project. I just downloaded the binary and run it. This single binary is standalone validating email address or is it connecting to your serverless backend?

**Comment by amaurymartiny** [comment]
The binary is running locally on your computer, it doesn't connect to the serverless backend at all.

**Comment by shinebayar-g** [comment]
I see, thanks for the reply. I noticed your online version prints little bit more output which is very helpful. Is it possible to get similar output from the binary?

**Comment by amaurymartiny** [comment]
Ah yeah, you're right. Could you create a new issue for this? I should be able to get to this quite fast.

(unless you want to create a PR yourself?)

**Comment by shinebayar-g** [comment]
Aight, I'm going to create a new issue. Unfortunately I have no idea about Rust language :D

**Comment by marcelinhov2** [comment]
I finally make it work man, OMFG!!!!!!

**Comment by amaurymartiny** [comment]
Nice! Would you mind sharing how you did it? Which service you chose etc.
